---
abstract: 'SSL/STARTTLS support for Net::POP3'
author:
  - 'Tomo <tomo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-POP3S
no_index:
  directory:
    - t
    - inc
requires:
  Authen::SASL: 2.15
  IO::Socket::SSL: 1
  Net::POP3: 2
version: 0.01
